/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.routemanagement.db;


import fi.morabotti.routemanagement.db.tables.Location;
import fi.morabotti.routemanagement.db.tables.Person;
import fi.morabotti.routemanagement.db.tables.PrimaryLocation;
import fi.morabotti.routemanagement.db.tables.Route;
import fi.morabotti.routemanagement.db.tables.Step;
import fi.morabotti.routemanagement.db.tables.StepItem;
import fi.morabotti.routemanagement.db.tables.Vehicle;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>location</code>.
     */
    public final Location LOCATION = Location.LOCATION;

    /**
     * The table <code>person</code>.
     */
    public final Person PERSON = Person.PERSON;

    /**
     * The table <code>primary_location</code>.
     */
    public final PrimaryLocation PRIMARY_LOCATION = PrimaryLocation.PRIMARY_LOCATION;

    /**
     * The table <code>route</code>.
     */
    public final Route ROUTE = Route.ROUTE;

    /**
     * The table <code>step</code>.
     */
    public final Step STEP = Step.STEP;

    /**
     * The table <code>step_item</code>.
     */
    public final StepItem STEP_ITEM = StepItem.STEP_ITEM;

    /**
     * The table <code>vehicle</code>.
     */
    public final Vehicle VEHICLE = Vehicle.VEHICLE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Location.LOCATION,
            Person.PERSON,
            PrimaryLocation.PRIMARY_LOCATION,
            Route.ROUTE,
            Step.STEP,
            StepItem.STEP_ITEM,
            Vehicle.VEHICLE);
    }
}
