/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.routemanagement.db;


import fi.morabotti.routemanagement.db.tables.Location;
import fi.morabotti.routemanagement.db.tables.Person;
import fi.morabotti.routemanagement.db.tables.PrimaryLocation;
import fi.morabotti.routemanagement.db.tables.Route;
import fi.morabotti.routemanagement.db.tables.Step;
import fi.morabotti.routemanagement.db.tables.StepItem;
import fi.morabotti.routemanagement.db.tables.Vehicle;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -870210414;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>location</code>.
     */
    public final Location LOCATION = fi.morabotti.routemanagement.db.tables.Location.LOCATION;

    /**
     * The table <code>person</code>.
     */
    public final Person PERSON = fi.morabotti.routemanagement.db.tables.Person.PERSON;

    /**
     * The table <code>primary_location</code>.
     */
    public final PrimaryLocation PRIMARY_LOCATION = fi.morabotti.routemanagement.db.tables.PrimaryLocation.PRIMARY_LOCATION;

    /**
     * The table <code>route</code>.
     */
    public final Route ROUTE = fi.morabotti.routemanagement.db.tables.Route.ROUTE;

    /**
     * The table <code>step</code>.
     */
    public final Step STEP = fi.morabotti.routemanagement.db.tables.Step.STEP;

    /**
     * The table <code>step_item</code>.
     */
    public final StepItem STEP_ITEM = fi.morabotti.routemanagement.db.tables.StepItem.STEP_ITEM;

    /**
     * The table <code>vehicle</code>.
     */
    public final Vehicle VEHICLE = fi.morabotti.routemanagement.db.tables.Vehicle.VEHICLE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Location.LOCATION,
            Person.PERSON,
            PrimaryLocation.PRIMARY_LOCATION,
            Route.ROUTE,
            Step.STEP,
            StepItem.STEP_ITEM,
            Vehicle.VEHICLE);
    }
}
