/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.routemanagement.db;


import fi.morabotti.routemanagement.db.tables.Location;
import fi.morabotti.routemanagement.db.tables.Person;
import fi.morabotti.routemanagement.db.tables.PrimaryLocation;
import fi.morabotti.routemanagement.db.tables.Route;
import fi.morabotti.routemanagement.db.tables.Step;
import fi.morabotti.routemanagement.db.tables.StepItem;
import fi.morabotti.routemanagement.db.tables.Vehicle;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index LOCATION_ID = Indexes0.LOCATION_ID;
    public static final Index PERSON_ID = Indexes0.PERSON_ID;
    public static final Index PRIMARY_LOCATION_FK_PRIMARY_LOCATION_LOCATION = Indexes0.PRIMARY_LOCATION_FK_PRIMARY_LOCATION_LOCATION;
    public static final Index PRIMARY_LOCATION_FK_PRIMARY_LOCATION_PERSON = Indexes0.PRIMARY_LOCATION_FK_PRIMARY_LOCATION_PERSON;
    public static final Index PRIMARY_LOCATION_ID = Indexes0.PRIMARY_LOCATION_ID;
    public static final Index ROUTE_FK_ROUTE_LOCATION = Indexes0.ROUTE_FK_ROUTE_LOCATION;
    public static final Index ROUTE_FK_ROUTE_VEHICLE = Indexes0.ROUTE_FK_ROUTE_VEHICLE;
    public static final Index ROUTE_ID = Indexes0.ROUTE_ID;
    public static final Index STEP_FK_STEP_LOCATION = Indexes0.STEP_FK_STEP_LOCATION;
    public static final Index STEP_FK_STEP_ROUTE = Indexes0.STEP_FK_STEP_ROUTE;
    public static final Index STEP_ID = Indexes0.STEP_ID;
    public static final Index STEP_ITEM_FK_STEP_ITEM_PERSON = Indexes0.STEP_ITEM_FK_STEP_ITEM_PERSON;
    public static final Index STEP_ITEM_FK_STEP_ITEM_STEP = Indexes0.STEP_ITEM_FK_STEP_ITEM_STEP;
    public static final Index STEP_ITEM_ID = Indexes0.STEP_ITEM_ID;
    public static final Index VEHICLE_ID = Indexes0.VEHICLE_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index LOCATION_ID = Internal.createIndex("id", Location.LOCATION, new OrderField[] { Location.LOCATION.ID }, true);
        public static Index PERSON_ID = Internal.createIndex("id", Person.PERSON, new OrderField[] { Person.PERSON.ID }, true);
        public static Index PRIMARY_LOCATION_FK_PRIMARY_LOCATION_LOCATION = Internal.createIndex("fk_primary_location_location", PrimaryLocation.PRIMARY_LOCATION, new OrderField[] { PrimaryLocation.PRIMARY_LOCATION.LOCATION_ID }, false);
        public static Index PRIMARY_LOCATION_FK_PRIMARY_LOCATION_PERSON = Internal.createIndex("fk_primary_location_person", PrimaryLocation.PRIMARY_LOCATION, new OrderField[] { PrimaryLocation.PRIMARY_LOCATION.PERSON_ID }, false);
        public static Index PRIMARY_LOCATION_ID = Internal.createIndex("id", PrimaryLocation.PRIMARY_LOCATION, new OrderField[] { PrimaryLocation.PRIMARY_LOCATION.ID }, true);
        public static Index ROUTE_FK_ROUTE_LOCATION = Internal.createIndex("fk_route_location", Route.ROUTE, new OrderField[] { Route.ROUTE.DESTINATION_ID }, false);
        public static Index ROUTE_FK_ROUTE_VEHICLE = Internal.createIndex("fk_route_vehicle", Route.ROUTE, new OrderField[] { Route.ROUTE.VEHICLE_ID }, false);
        public static Index ROUTE_ID = Internal.createIndex("id", Route.ROUTE, new OrderField[] { Route.ROUTE.ID }, true);
        public static Index STEP_FK_STEP_LOCATION = Internal.createIndex("fk_step_location", Step.STEP, new OrderField[] { Step.STEP.LOCATION_ID }, false);
        public static Index STEP_FK_STEP_ROUTE = Internal.createIndex("fk_step_route", Step.STEP, new OrderField[] { Step.STEP.ROUTE_ID }, false);
        public static Index STEP_ID = Internal.createIndex("id", Step.STEP, new OrderField[] { Step.STEP.ID }, true);
        public static Index STEP_ITEM_FK_STEP_ITEM_PERSON = Internal.createIndex("fk_step_item_person", StepItem.STEP_ITEM, new OrderField[] { StepItem.STEP_ITEM.PERSON_ID }, false);
        public static Index STEP_ITEM_FK_STEP_ITEM_STEP = Internal.createIndex("fk_step_item_step", StepItem.STEP_ITEM, new OrderField[] { StepItem.STEP_ITEM.STEP_ID }, false);
        public static Index STEP_ITEM_ID = Internal.createIndex("id", StepItem.STEP_ITEM, new OrderField[] { StepItem.STEP_ITEM.ID }, true);
        public static Index VEHICLE_ID = Internal.createIndex("id", Vehicle.VEHICLE, new OrderField[] { Vehicle.VEHICLE.ID }, true);
    }
}
