/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.routemanagement.db;


import fi.morabotti.routemanagement.db.tables.Location;
import fi.morabotti.routemanagement.db.tables.Person;
import fi.morabotti.routemanagement.db.tables.PrimaryLocation;
import fi.morabotti.routemanagement.db.tables.Route;
import fi.morabotti.routemanagement.db.tables.Step;
import fi.morabotti.routemanagement.db.tables.StepItem;
import fi.morabotti.routemanagement.db.tables.Vehicle;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>location</code>.
     */
    public static final Location LOCATION = fi.morabotti.routemanagement.db.tables.Location.LOCATION;

    /**
     * The table <code>person</code>.
     */
    public static final Person PERSON = fi.morabotti.routemanagement.db.tables.Person.PERSON;

    /**
     * The table <code>primary_location</code>.
     */
    public static final PrimaryLocation PRIMARY_LOCATION = fi.morabotti.routemanagement.db.tables.PrimaryLocation.PRIMARY_LOCATION;

    /**
     * The table <code>route</code>.
     */
    public static final Route ROUTE = fi.morabotti.routemanagement.db.tables.Route.ROUTE;

    /**
     * The table <code>step</code>.
     */
    public static final Step STEP = fi.morabotti.routemanagement.db.tables.Step.STEP;

    /**
     * The table <code>step_item</code>.
     */
    public static final StepItem STEP_ITEM = fi.morabotti.routemanagement.db.tables.StepItem.STEP_ITEM;

    /**
     * The table <code>vehicle</code>.
     */
    public static final Vehicle VEHICLE = fi.morabotti.routemanagement.db.tables.Vehicle.VEHICLE;
}
