/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.routemanagement.db;


import fi.morabotti.routemanagement.db.tables.Location;
import fi.morabotti.routemanagement.db.tables.Person;
import fi.morabotti.routemanagement.db.tables.PrimaryLocation;
import fi.morabotti.routemanagement.db.tables.Route;
import fi.morabotti.routemanagement.db.tables.Step;
import fi.morabotti.routemanagement.db.tables.StepItem;
import fi.morabotti.routemanagement.db.tables.Vehicle;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>location</code>.
     */
    public static final Location LOCATION = Location.LOCATION;

    /**
     * The table <code>person</code>.
     */
    public static final Person PERSON = Person.PERSON;

    /**
     * The table <code>primary_location</code>.
     */
    public static final PrimaryLocation PRIMARY_LOCATION = PrimaryLocation.PRIMARY_LOCATION;

    /**
     * The table <code>route</code>.
     */
    public static final Route ROUTE = Route.ROUTE;

    /**
     * The table <code>step</code>.
     */
    public static final Step STEP = Step.STEP;

    /**
     * The table <code>step_item</code>.
     */
    public static final StepItem STEP_ITEM = StepItem.STEP_ITEM;

    /**
     * The table <code>vehicle</code>.
     */
    public static final Vehicle VEHICLE = Vehicle.VEHICLE;
}
