/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.routemanagement.db.tables;


import fi.morabotti.routemanagement.db.DefaultSchema;
import fi.morabotti.routemanagement.db.Indexes;
import fi.morabotti.routemanagement.db.Keys;
import fi.morabotti.routemanagement.db.tables.records.StepItemRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StepItem extends TableImpl<StepItemRecord> {

    private static final long serialVersionUID = 438960213;

    /**
     * The reference instance of <code>step_item</code>
     */
    public static final StepItem STEP_ITEM = new StepItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StepItemRecord> getRecordType() {
        return StepItemRecord.class;
    }

    /**
     * The column <code>step_item.id</code>.
     */
    public final TableField<StepItemRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>step_item.person_id</code>.
     */
    public final TableField<StepItemRecord, Long> PERSON_ID = createField("person_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>step_item.step_id</code>.
     */
    public final TableField<StepItemRecord, Long> STEP_ID = createField("step_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>step_item.deleted_at</code>.
     */
    public final TableField<StepItemRecord, Timestamp> DELETED_AT = createField("deleted_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>step_item</code> table reference
     */
    public StepItem() {
        this(DSL.name("step_item"), null);
    }

    /**
     * Create an aliased <code>step_item</code> table reference
     */
    public StepItem(String alias) {
        this(DSL.name(alias), STEP_ITEM);
    }

    /**
     * Create an aliased <code>step_item</code> table reference
     */
    public StepItem(Name alias) {
        this(alias, STEP_ITEM);
    }

    private StepItem(Name alias, Table<StepItemRecord> aliased) {
        this(alias, aliased, null);
    }

    private StepItem(Name alias, Table<StepItemRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> StepItem(Table<O> child, ForeignKey<O, StepItemRecord> key) {
        super(child, key, STEP_ITEM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.STEP_ITEM_FK_STEP_ITEM_PERSON, Indexes.STEP_ITEM_FK_STEP_ITEM_STEP, Indexes.STEP_ITEM_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StepItemRecord, Long> getIdentity() {
        return Keys.IDENTITY_STEP_ITEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StepItemRecord>> getKeys() {
        return Arrays.<UniqueKey<StepItemRecord>>asList(Keys.KEY_STEP_ITEM_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<StepItemRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<StepItemRecord, ?>>asList(Keys.FK_STEP_ITEM_PERSON, Keys.FK_STEP_ITEM_STEP);
    }

    public Person person() {
        return new Person(this, Keys.FK_STEP_ITEM_PERSON);
    }

    public Step step() {
        return new Step(this, Keys.FK_STEP_ITEM_STEP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StepItem as(String alias) {
        return new StepItem(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StepItem as(Name alias) {
        return new StepItem(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StepItem rename(String name) {
        return new StepItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StepItem rename(Name name) {
        return new StepItem(name, null);
    }
}
