/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.routemanagement.db.tables.records;


import fi.morabotti.routemanagement.db.tables.Location;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LocationRecord extends TableRecordImpl<LocationRecord> implements Record7<Long, String, String, String, BigDecimal, BigDecimal, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>location.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>location.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>location.address</code>.
     */
    public void setAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>location.address</code>.
     */
    public String getAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>location.zip</code>.
     */
    public void setZip(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>location.zip</code>.
     */
    public String getZip() {
        return (String) get(2);
    }

    /**
     * Setter for <code>location.city</code>.
     */
    public void setCity(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>location.city</code>.
     */
    public String getCity() {
        return (String) get(3);
    }

    /**
     * Setter for <code>location.latitude</code>.
     */
    public void setLatitude(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>location.latitude</code>.
     */
    public BigDecimal getLatitude() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>location.longitude</code>.
     */
    public void setLongitude(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>location.longitude</code>.
     */
    public BigDecimal getLongitude() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>location.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>location.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, String, BigDecimal, BigDecimal, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, String, BigDecimal, BigDecimal, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Location.LOCATION.ID;
    }

    @Override
    public Field<String> field2() {
        return Location.LOCATION.ADDRESS;
    }

    @Override
    public Field<String> field3() {
        return Location.LOCATION.ZIP;
    }

    @Override
    public Field<String> field4() {
        return Location.LOCATION.CITY;
    }

    @Override
    public Field<BigDecimal> field5() {
        return Location.LOCATION.LATITUDE;
    }

    @Override
    public Field<BigDecimal> field6() {
        return Location.LOCATION.LONGITUDE;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Location.LOCATION.DELETED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAddress();
    }

    @Override
    public String component3() {
        return getZip();
    }

    @Override
    public String component4() {
        return getCity();
    }

    @Override
    public BigDecimal component5() {
        return getLatitude();
    }

    @Override
    public BigDecimal component6() {
        return getLongitude();
    }

    @Override
    public LocalDateTime component7() {
        return getDeletedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAddress();
    }

    @Override
    public String value3() {
        return getZip();
    }

    @Override
    public String value4() {
        return getCity();
    }

    @Override
    public BigDecimal value5() {
        return getLatitude();
    }

    @Override
    public BigDecimal value6() {
        return getLongitude();
    }

    @Override
    public LocalDateTime value7() {
        return getDeletedAt();
    }

    @Override
    public LocationRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public LocationRecord value2(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public LocationRecord value3(String value) {
        setZip(value);
        return this;
    }

    @Override
    public LocationRecord value4(String value) {
        setCity(value);
        return this;
    }

    @Override
    public LocationRecord value5(BigDecimal value) {
        setLatitude(value);
        return this;
    }

    @Override
    public LocationRecord value6(BigDecimal value) {
        setLongitude(value);
        return this;
    }

    @Override
    public LocationRecord value7(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public LocationRecord values(Long value1, String value2, String value3, String value4, BigDecimal value5, BigDecimal value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LocationRecord
     */
    public LocationRecord() {
        super(Location.LOCATION);
    }

    /**
     * Create a detached, initialised LocationRecord
     */
    public LocationRecord(Long id, String address, String zip, String city, BigDecimal latitude, BigDecimal longitude, LocalDateTime deletedAt) {
        super(Location.LOCATION);

        setId(id);
        setAddress(address);
        setZip(zip);
        setCity(city);
        setLatitude(latitude);
        setLongitude(longitude);
        setDeletedAt(deletedAt);
    }
}
