/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.routemanagement.db.tables.records;


import fi.morabotti.routemanagement.db.tables.PrimaryLocation;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrimaryLocationRecord extends TableRecordImpl<PrimaryLocationRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 291921980;

    /**
     * Setter for <code>primary_location.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>primary_location.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>primary_location.person_id</code>.
     */
    public void setPersonId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>primary_location.person_id</code>.
     */
    public Long getPersonId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>primary_location.location_id</code>.
     */
    public void setLocationId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>primary_location.location_id</code>.
     */
    public Long getLocationId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PrimaryLocation.PRIMARY_LOCATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PrimaryLocation.PRIMARY_LOCATION.PERSON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return PrimaryLocation.PRIMARY_LOCATION.LOCATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrimaryLocationRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrimaryLocationRecord value2(Long value) {
        setPersonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrimaryLocationRecord value3(Long value) {
        setLocationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrimaryLocationRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PrimaryLocationRecord
     */
    public PrimaryLocationRecord() {
        super(PrimaryLocation.PRIMARY_LOCATION);
    }

    /**
     * Create a detached, initialised PrimaryLocationRecord
     */
    public PrimaryLocationRecord(Long id, Long personId, Long locationId) {
        super(PrimaryLocation.PRIMARY_LOCATION);

        set(0, id);
        set(1, personId);
        set(2, locationId);
    }
}
