/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.routemanagement.db.tables.records;


import fi.morabotti.routemanagement.db.tables.Route;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RouteRecord extends TableRecordImpl<RouteRecord> implements Record5<Long, LocalDateTime, Long, Long, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>route.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>route.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>route.start_time</code>.
     */
    public void setStartTime(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>route.start_time</code>.
     */
    public LocalDateTime getStartTime() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>route.vehicle_id</code>.
     */
    public void setVehicleId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>route.vehicle_id</code>.
     */
    public Long getVehicleId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>route.destination_id</code>.
     */
    public void setDestinationId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>route.destination_id</code>.
     */
    public Long getDestinationId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>route.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>route.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, LocalDateTime, Long, Long, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, LocalDateTime, Long, Long, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Route.ROUTE.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return Route.ROUTE.START_TIME;
    }

    @Override
    public Field<Long> field3() {
        return Route.ROUTE.VEHICLE_ID;
    }

    @Override
    public Field<Long> field4() {
        return Route.ROUTE.DESTINATION_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Route.ROUTE.DELETED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getStartTime();
    }

    @Override
    public Long component3() {
        return getVehicleId();
    }

    @Override
    public Long component4() {
        return getDestinationId();
    }

    @Override
    public LocalDateTime component5() {
        return getDeletedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getStartTime();
    }

    @Override
    public Long value3() {
        return getVehicleId();
    }

    @Override
    public Long value4() {
        return getDestinationId();
    }

    @Override
    public LocalDateTime value5() {
        return getDeletedAt();
    }

    @Override
    public RouteRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public RouteRecord value2(LocalDateTime value) {
        setStartTime(value);
        return this;
    }

    @Override
    public RouteRecord value3(Long value) {
        setVehicleId(value);
        return this;
    }

    @Override
    public RouteRecord value4(Long value) {
        setDestinationId(value);
        return this;
    }

    @Override
    public RouteRecord value5(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public RouteRecord values(Long value1, LocalDateTime value2, Long value3, Long value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RouteRecord
     */
    public RouteRecord() {
        super(Route.ROUTE);
    }

    /**
     * Create a detached, initialised RouteRecord
     */
    public RouteRecord(Long id, LocalDateTime startTime, Long vehicleId, Long destinationId, LocalDateTime deletedAt) {
        super(Route.ROUTE);

        setId(id);
        setStartTime(startTime);
        setVehicleId(vehicleId);
        setDestinationId(destinationId);
        setDeletedAt(deletedAt);
    }
}
