/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.routemanagement.db.tables.records;


import fi.morabotti.routemanagement.db.tables.Route;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RouteRecord extends TableRecordImpl<RouteRecord> implements Record5<Long, Timestamp, Long, Long, Timestamp> {

    private static final long serialVersionUID = 879444999;

    /**
     * Setter for <code>route.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>route.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>route.start_time</code>.
     */
    public void setStartTime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>route.start_time</code>.
     */
    public Timestamp getStartTime() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>route.vehicle_id</code>.
     */
    public void setVehicleId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>route.vehicle_id</code>.
     */
    public Long getVehicleId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>route.destination_id</code>.
     */
    public void setDestinationId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>route.destination_id</code>.
     */
    public Long getDestinationId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>route.deleted_at</code>.
     */
    public void setDeletedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>route.deleted_at</code>.
     */
    public Timestamp getDeletedAt() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Timestamp, Long, Long, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Timestamp, Long, Long, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Route.ROUTE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Route.ROUTE.START_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Route.ROUTE.VEHICLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Route.ROUTE.DESTINATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Route.ROUTE.DELETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getVehicleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getDestinationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getVehicleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getDestinationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteRecord value2(Timestamp value) {
        setStartTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteRecord value3(Long value) {
        setVehicleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteRecord value4(Long value) {
        setDestinationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteRecord value5(Timestamp value) {
        setDeletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteRecord values(Long value1, Timestamp value2, Long value3, Long value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RouteRecord
     */
    public RouteRecord() {
        super(Route.ROUTE);
    }

    /**
     * Create a detached, initialised RouteRecord
     */
    public RouteRecord(Long id, Timestamp startTime, Long vehicleId, Long destinationId, Timestamp deletedAt) {
        super(Route.ROUTE);

        set(0, id);
        set(1, startTime);
        set(2, vehicleId);
        set(3, destinationId);
        set(4, deletedAt);
    }
}
