/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.routemanagement.db.tables.records;


import fi.morabotti.routemanagement.db.tables.StepItem;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StepItemRecord extends TableRecordImpl<StepItemRecord> implements Record4<Long, Long, Long, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>step_item.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>step_item.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>step_item.person_id</code>.
     */
    public void setPersonId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>step_item.person_id</code>.
     */
    public Long getPersonId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>step_item.step_id</code>.
     */
    public void setStepId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>step_item.step_id</code>.
     */
    public Long getStepId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>step_item.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>step_item.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, Long, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, Long, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return StepItem.STEP_ITEM.ID;
    }

    @Override
    public Field<Long> field2() {
        return StepItem.STEP_ITEM.PERSON_ID;
    }

    @Override
    public Field<Long> field3() {
        return StepItem.STEP_ITEM.STEP_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return StepItem.STEP_ITEM.DELETED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getPersonId();
    }

    @Override
    public Long component3() {
        return getStepId();
    }

    @Override
    public LocalDateTime component4() {
        return getDeletedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getPersonId();
    }

    @Override
    public Long value3() {
        return getStepId();
    }

    @Override
    public LocalDateTime value4() {
        return getDeletedAt();
    }

    @Override
    public StepItemRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public StepItemRecord value2(Long value) {
        setPersonId(value);
        return this;
    }

    @Override
    public StepItemRecord value3(Long value) {
        setStepId(value);
        return this;
    }

    @Override
    public StepItemRecord value4(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public StepItemRecord values(Long value1, Long value2, Long value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StepItemRecord
     */
    public StepItemRecord() {
        super(StepItem.STEP_ITEM);
    }

    /**
     * Create a detached, initialised StepItemRecord
     */
    public StepItemRecord(Long id, Long personId, Long stepId, LocalDateTime deletedAt) {
        super(StepItem.STEP_ITEM);

        setId(id);
        setPersonId(personId);
        setStepId(stepId);
        setDeletedAt(deletedAt);
    }
}
