/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.routemanagement.db.tables.records;


import fi.morabotti.routemanagement.db.tables.Step;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StepRecord extends TableRecordImpl<StepRecord> implements Record5<Long, Integer, Long, Long, Timestamp> {

    private static final long serialVersionUID = 628963741;

    /**
     * Setter for <code>step.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>step.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>step.order</code>.
     */
    public void setOrder(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>step.order</code>.
     */
    public Integer getOrder() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>step.route_id</code>.
     */
    public void setRouteId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>step.route_id</code>.
     */
    public Long getRouteId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>step.location_id</code>.
     */
    public void setLocationId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>step.location_id</code>.
     */
    public Long getLocationId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>step.deleted_at</code>.
     */
    public void setDeletedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>step.deleted_at</code>.
     */
    public Timestamp getDeletedAt() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Integer, Long, Long, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Integer, Long, Long, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Step.STEP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Step.STEP.ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Step.STEP.ROUTE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Step.STEP.LOCATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Step.STEP.DELETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getRouteId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getRouteId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StepRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StepRecord value2(Integer value) {
        setOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StepRecord value3(Long value) {
        setRouteId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StepRecord value4(Long value) {
        setLocationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StepRecord value5(Timestamp value) {
        setDeletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StepRecord values(Long value1, Integer value2, Long value3, Long value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StepRecord
     */
    public StepRecord() {
        super(Step.STEP);
    }

    /**
     * Create a detached, initialised StepRecord
     */
    public StepRecord(Long id, Integer order, Long routeId, Long locationId, Timestamp deletedAt) {
        super(Step.STEP);

        set(0, id);
        set(1, order);
        set(2, routeId);
        set(3, locationId);
        set(4, deletedAt);
    }
}
