/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.routemanagement.db.tables.records;


import fi.morabotti.routemanagement.db.tables.StepItem;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StepItemRecord extends TableRecordImpl<StepItemRecord> implements Record4<Long, Long, Long, Timestamp> {

    private static final long serialVersionUID = -567202060;

    /**
     * Setter for <code>step_item.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>step_item.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>step_item.person_id</code>.
     */
    public void setPersonId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>step_item.person_id</code>.
     */
    public Long getPersonId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>step_item.step_id</code>.
     */
    public void setStepId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>step_item.step_id</code>.
     */
    public Long getStepId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>step_item.deleted_at</code>.
     */
    public void setDeletedAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>step_item.deleted_at</code>.
     */
    public Timestamp getDeletedAt() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, Long, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, Long, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return StepItem.STEP_ITEM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return StepItem.STEP_ITEM.PERSON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return StepItem.STEP_ITEM.STEP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return StepItem.STEP_ITEM.DELETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getStepId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getStepId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StepItemRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StepItemRecord value2(Long value) {
        setPersonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StepItemRecord value3(Long value) {
        setStepId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StepItemRecord value4(Timestamp value) {
        setDeletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StepItemRecord values(Long value1, Long value2, Long value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StepItemRecord
     */
    public StepItemRecord() {
        super(StepItem.STEP_ITEM);
    }

    /**
     * Create a detached, initialised StepItemRecord
     */
    public StepItemRecord(Long id, Long personId, Long stepId, Timestamp deletedAt) {
        super(StepItem.STEP_ITEM);

        set(0, id);
        set(1, personId);
        set(2, stepId);
        set(3, deletedAt);
    }
}
