/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.routemanagement.db.tables.records;


import fi.morabotti.routemanagement.db.tables.Vehicle;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehicleRecord extends TableRecordImpl<VehicleRecord> implements Record3<Long, String, Timestamp> {

    private static final long serialVersionUID = -1700124892;

    /**
     * Setter for <code>vehicle.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>vehicle.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>vehicle.license_number</code>.
     */
    public void setLicenseNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>vehicle.license_number</code>.
     */
    public String getLicenseNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vehicle.deleted_at</code>.
     */
    public void setDeletedAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>vehicle.deleted_at</code>.
     */
    public Timestamp getDeletedAt() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Vehicle.VEHICLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Vehicle.VEHICLE.LICENSE_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Vehicle.VEHICLE.DELETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLicenseNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLicenseNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehicleRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehicleRecord value2(String value) {
        setLicenseNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehicleRecord value3(Timestamp value) {
        setDeletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehicleRecord values(Long value1, String value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VehicleRecord
     */
    public VehicleRecord() {
        super(Vehicle.VEHICLE);
    }

    /**
     * Create a detached, initialised VehicleRecord
     */
    public VehicleRecord(Long id, String licenseNumber, Timestamp deletedAt) {
        super(Vehicle.VEHICLE);

        set(0, id);
        set(1, licenseNumber);
        set(2, deletedAt);
    }
}
