import { FC } from 'react';

export const DummyComponent: FC = () => {
  return (
    <div>
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
    </div>
  );
};
