export enum Client {
  GET_VEHICLES,
  CREATE_VEHICLE,
  GET_VEHICLE_BY_ID,
  UPDATE_VEHICLE_BY_ID,
  DELETE_VEHICLE_BY_ID,
  GET_PERSONS,
  CREATE_PERSON,
  GET_PERSON_BY_ID,
  UPDATE_PERSON_BY_ID,
  DELETE_PERSON_BY_ID,
  GET_LOCATIONS,
  CREATE_LOCATION,
  GET_LOCATION_BY_ID,
  UPDATE_LOCATION_BY_ID,
  DELETE_LOCATION_BY_ID,
  ADD_LOCATION_AS_PRIMARY,
  REMOVE_LOCATION_AS_PRIMARY,
  GET_ROUTES,
  CREATE_ROUTE,
  GET_ROUTE_BY_ID,
  UPDATE_ROUTE_BY_ID,
  DELETE_ROUTE_BY_ID,
  CREATE_ROUTE_STEP,
  UPDATE_ROUTE_STEP_BY_ID,
  DELETE_ROUTE_STEP_BY_ID,
  ADD_ROUTE_STEP_ITEM,
  DELETE_ROUTE_STEP_ITEM
}

export enum RouteAuthType {
  AUTH = 'auth',
  PUBLIC = 'public'
}

export enum LocalStorageKey {
  TOKEN = 'token',
  APPLICATION_CACHE = 'rm-cache'
}

export enum CrudState {
  LIST,
  VIEW,
  UPDATE,
  DELETE
}
